
erDiagram
    user ||--|| userStatuses : lookup
    user ||--|| profileStatuses: lookup
    user ||--|{ records : creates
    records ||--|| userStatuses: lookup
    user ||--|| userAuths : authenticates
    
    user ||--|| profile: contains
    userStatistics ||--|| user: contains
    profile ||--o{ userAchievements: contains
    userRsvp ||--|| user: contains
    userConnections ||--|| user: contains
    connectionStatuses ||--|| userConnections: lookup
    profile ||--|| degrees: lookup
    userAchievements ||--|| achievements: lookup

    user ||--o{ bulletin: creates
    user ||--o{ comments: creates
    user ||--o{ donations: creates
    user ||--o{ events: creates
    admin ||--o{ bulletin : reviews
    admin ||--o{ events : reviews
    admin ||--o{ user : manages 
    donations ||--|| donationStatuses: lookup
    bulletin ||--|| contentStatuses: lookup
    events ||--|| contentStatuses: lookup
    events ||--|| eventCategories: lookup
    events ||--|| location: contains

    %% 1XX - Degree-related
    degrees {
        string id PK
        string degreeName "e.g. BS Mechanical Engineering, BS Civil Engineering, etc."
        string degreeAbbr "e.g. BSME, BSCE, etc."
    }
    %% 2XX - userConnections status
    connectionStatuses {
        string id PK
        string connectionName "e.g. Pending, Accepted, Blocked, etc."
    }
    %% 3XX - Content-related
    contentStatuses {
        string id PK
        string statusName "e.g. Pending, Approved, Rejected"
    }
    %% 4XX - User-related
    %% Content from banned users are automatically hidden from view
    %% Suspended users still maintain content visibility
    %% Suspended users cannot create or edit content, nor can they donate
    %% Ditto for banned users
    %% In all cases, their profile will show their status e.g. [SUSPENDED], [BANNED]
    userStatuses {
        string id PK
        string statusName "e.g. Regular, Official, Banned, etc."
    }
    %% 5XX - Donation-related
    donationStatuses {
        string id PK
        string statusName "e.g. Processing, Completed, Failed"
    }
    %% 6XX - Event-related
    eventCategories {
        string id PK
        string eventCategoryName "e.g. Networking, Sports, Online, etc."
    }
    %% 7XX - Profile status
    profileStatuses {
        string id PK
        string statusName "e.g. Private, Connections Only, Public, etc."
    }
    %% 8XX - Notification-related
    notificationTypes {
        string id PK
        string notificationTypeName "e.g. Connection, Event, etc."
    }

    user {
        string id PK
        string userStatusId FK
        string currentRecordId FK
        string profileStatusId FK
    }
    records {
        string id PK "New record created every time user status changes"
        string userId FK
        string adminId FK
        string userStatusId FK
        date dateCreated "Defaults to timestamp of query, immutable"
        string description "Describes the nature of status"
        date dateExpires "`NULL` for statuses with no expiry"
    }
    userAuths {
        string userId PK,FK
        string email "Used as login identifier"
        string passwordHash "Hashed password (never store plain text)"
        datetime lastLogin
    }

    userAchievements {
        string userId PK,FK
        string achievementId PK,FK
        shortint achievementTier PK,FK
        datetime achievedDate "Defaults to timestamp of acquisition, immutable"
    }
    achievements {
        string id PK
        int achievementCategory "Internal, used for achievement categories"
        shortint achievementTier PK
        string achievementTitle
        string achievementDescription
        string achievementIcon
    }
    userConnections {
        string userId PK,FK
        string friendId PK,FK
        string connectionStatusId
        date dateUpdated
    }
    userRsvp {
        string userId PK,FK
        string eventId PK,FK
        boolean isAttending
    }
    userStatistics {
        string userId PK,FK
        int userConnections
        int eventsAttended
        %% Possibly unused, whatever
        int eventsCreated
        int bulletinsCreated
        int commentsWritten
        int achievements
        float donatedAmount
        date dateRegistered
    }
    profile {
        string userId PK,FK
        string userName
        string bio
        string email
        string phone
        string location
        string currentJob
        string company
        string profileImage
        string degreeId FK
        smallint batch
        date birthday
    }

    admin {
        string id PK
        string passwordHash "Hashed password (never store plain text)"
        datetime lastLogin
    }

    bulletin {
        string id PK
        string adminId FK
        string authorId FK
        string contentStatusId FK
        datetime bulletinDate
        datetime reviewDate "NULL if not reviewed"
        string title
        int readTimeMinutes
        text content
        string bulletinImage
    }
    events {
        string id PK
        string adminId FK
        string authorId FK
        string statusId FK
        string locationId FK
        string eventCategoryId FK
        datetime eventDate
        datetime reviewDate "NULL if not reviewed"
        string title
        text description
        time startTime
        time endTime
        shortint responses
        string modality
        string eventImage
    }

    location {
        string id PK
        string regionCode
        string province
        string provinceCode
        string cityMunicipality
        string cityCode
        string barangay
        string landmark
        string street
        float lat
        float lng
    }
    comments {
        string id PK
        string userId FK
        string bulletinId FK
        datetime commentDate
        string comment
        shortint likes
    }
    donations {
        string id PK
        string userId FK "NULL if anonymous"
        string donationReference "Reference ID from payment"
        string donationStatusId FK
        datetime donationDate
        float donationAmount
        money donationAmountPhp "Human-readable format"
        boolean donationAnonymous 
        string donationEmail
    }
    notifications {
        string id PK
        string userId FK
        string notificationTypeId FK
        string notificationMessage
        datetime notificationDate
        boolean isRead
    }